application: mcottondesign3-hrd
version: alsok
runtime: python27
api_version: 1
threadsafe: true

derived_file_type:
- python_precompiled

libraries:
- name: webapp2
  version: latest

- name: django
  version: "1.2"

handlers:
- url: /images
  static_dir: templates/_images

- url: /css
  static_dir: templates/_css

- url: /js
  static_dir: templates/_js

- url: /static
  static_dir: templates/_static

- url: /favicon.ico
  static_files: templates/_images/favicon.ico
  upload: templates/_images/favicon.ico

- url: /robots.txt
  static_files: templates/_images/robots.txt
  upload: templates/_images/favicon.ico

- url: /.*
  script: main.app
